### ISSUE TITLE
Upgrading the node cli from v1.0.0 to v1.1.0-beta.5 leads to schain_allocation.yml  error

### ISSUE THREAD

**Issue by Chainode** [skalenetwork/skale-node#182]
After registering the validator and the node successfully with v1.0.0 version, the upgrading procedure was started.

The env variables were updated, the .skale/node_data/skale.db was removed before skale node update and node cli was updated to v1.1.0-beta.5.

The result of running sudo skale node update config.env is:
```
sudo skale node update config.env
Are you sure you want to update SKALE node software? [y/N]: y
Updating the node...
Command execution failed with [Errno 2] No such file or directory: '/home/harmm11/.skale/config/schain_allocation.yml'. Recheck your inputs
Traceback (most recent call last):
  File "main.py", line 111, in <module>
  File "site-packages/click/core.py", line 829, in **call**
  File "site-packages/click/core.py", line 782, in main
  File "site-packages/click/core.py", line 1259, in invoke
  File "site-packages/click/core.py", line 1259, in invoke
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 610, in invoke
  File "cli/node.py", line 156, in update_node
  File "core/node.py", line 184, in update
  File "core/host.py", line 73, in prepare_host
  File "core/resources.py", line 133, in update_resource_allocation
  File "core/resources.py", line 77, in compose_resource_allocation_config
  File "core/helper.py", line 81, in safe_load_yml
FileNotFoundError: [Errno 2] No such file or directory: '/home/harmm11/.skale/config/schain_allocation.yml'



┆Issue is synchronized with this [Jira Task](https://skalelabs.atlassian.net/browse/SKALE-3770)

**Comment by ebruengwall-ant** [comment]
@EvgeniyZZ This is an upgrade from mainnet version to testnet latest version. He was able to checkout manually from `.skale/config` folder but he should be able to upgrade without manual work with **skale node update**

**Comment by dmytrotkk** [comment]
Hey @Chainode!
Thank you for reporting this.

This issue is caused by the incompatibility between versions of `node-cli` and `skale-node`. 
`schain_allocation.yml` file mentioned in the issue was added in [1.2.0 Testnet](https://github.com/skalenetwork/skale-node/releases/tag/1.2.0-testnet) release of SKALE Node (see release notes). So to use `node-cli` v1.1.0-beta.5 you should update `skale-node` tag (`CONTAINER_CONFIGS_STREAM` variable in your `.env` file) to [1.2.0-testnet](https://github.com/skalenetwork/skale-node/releases/tag/1.2.0-testnet) or newer. 

Sorry for this inconvenience, in the current implementation we don't have compatibility errors handling in our components which may cause such problems, but we're going to resolve this issue in the upcoming versions.

**Comment by Chainode** [comment]
Hey @dmitry-tk!

Sure, no problem. 

I see but I used 1.3.2-testnet for CONTAINER_CONFIGS_STREAM variable in the .env file. This was specified in the documentation for the upgrade and is also newer than 1.2.0-testnet. This means that the error appeared although the requirement is fulfilled.

**Comment by gannakulikova** [comment]
@Chainode Hi! Please be advised that the fix is ready and will be coming as a part of the next TestNet update :)
